spring:
  application:
    name: eureka-server
server:
  port: 8761
  enableSelfPreservation: true  # Auto-preservación activada
  renewalPercentThreshold: 0.70  # Umbral de renovacion a 70%
  evictionIntervalTimerInMs: 60000  # Verificación cada 60s

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
