spring:
  application:
    name: eureka-server
server:
  port: 8761
  enableSelfPreservation: true  # Habilita el modo de auto-preservacion
  renewalPercentThreshold: 0.85  # Reduce el umbral del 85% (default) a 75%
  evictionIntervalTimerInMs: 60000  # Cada 60s, Eureka verifica instancias no renovadas

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false